"""
生成 data.js - 用 Python 字典方式生成，零语法错误
"""
import json
import os

# 简化后的结构：直接用 Python dict 表达
# 中文地名、英文地名等信息分开定义

# ---- 景点介绍 (中文 + 英文) ----
spots_data = {
  # 米兰
  "milano-malpensa": {"zh": ("米兰马尔彭萨机场", "机场", "Milan Malpensa Airport",
    "意大利最大机场之一，阿提哈航空 EY81 抵达门户。",
    ["T1 到达层集合点", "ATM/换汇窗口", "去博尔扎诺包车集合"],
    ["提前 24h 在线 check-in", "阿布扎比转机可领餐券", "包车司机举牌接机"]),
    "en": ("Milan Malpensa Airport", "Airport", "Milan Malpensa Airport",
      "One of Italy's largest airports — Etihad EY81 arrives here.",
      ["T1 arrivals meeting point", "ATM / FX counters", "Dolomites driver pickup"],
      ["Check in online 24h ahead", "AUH transit meal voucher", "Driver holds nameplate"])},
  "milan-central": {"zh": ("米兰中央火车站", "交通枢纽", "Milano Centrale",
    "意大利北部最重要的铁路枢纽，前往威尼斯/佛罗伦萨/多洛米蒂均从此出发。",
    ["Frecciarossa 高速列车站台", "行李寄存柜", "Trenitalia 自助机"],
    ["Italo 票价常较 Trenitalia 便宜", "提前 14 天购早鸟票", "站台需提前看清"]),
    "en": ("Milano Centrale", "Hub", "Milano Centrale",
      "Northern Italy's main rail hub — Frecciarossa to Dolomites / Venice / Florence.",
      ["Frecciarossa platforms", "Luggage lockers", "Trenitalia self-service kiosks"],
      ["Italo often cheaper than Trenitalia", "Book 14 days ahead for early-bird", "Check platform on screens"])},
  # 多洛米蒂
  "brixen": {"zh": ("Brixen / Bressanone", "多洛米蒂门户小镇", "Brixen Bressanone",
    "多洛米蒂南部门户小镇，持有 BrixenCard 可免费乘坐所有公交并享多项折扣。",
    ["主教教堂广场", "Isarco 河沿岸散步", "Pharmazie Museum"],
    ["酒店提供 BrixenCard", "可作为刀锋山/休斯高原的中转站", "镇上餐厅性价比高"]),
    "en": ("Brixen / Bressanone", "Dolomiti Gateway", "Brixen Bressanone",
      "Southern gateway to the Dolomites — BrixenCard covers all buses and many discounts.",
      ["Cathedral square", "Isarco riverside walk", "Pharmacy Museum"],
      ["Hotel issues the BrixenCard", "Best base for Seceda and Alpe di Siusi", "Great local restaurants"])},
  "seceda": {"zh": ("Seceda 刀锋山", "多洛米蒂地标", "Seceda viewpoint",
    "多洛米蒂最具辨识度的刀锋形山脊，《孤独星球》封面取景地。",
    ["Seceda 观景台俯视 Geisleralmpe 草甸", "从 Ortisei 缆车直达", "早晨金黄色阳光最佳"],
    ["8:30 前到达 Ortisei 缆车站", "山顶风大备外套", "建议 9 月底穿轻羽绒"]),
    "en": ("Seceda Ridge", "Dolomite Landmark", "Seceda viewpoint",
      "The Dolomites' most iconic blade ridge — Lonely Planet cover.",
      ["Viewpoint over Geisleralmpe", "Cable car from Ortisei", "Golden morning light"],
      ["Reach Ortisei station before 8:30", "Wind is strong on top", "Light down jacket in autumn"])},
  "alpe-di-siusi": {"zh": ("Alpe di Siusi 休斯高原", "多洛米蒂高山草甸", "Alpe di Siusi Seiser Alm",
    "欧洲最大的高山草甸，黄绿相间，秋色渐染时如油画。",
    ["Compatsch 缆车上山", "Panorama 步道徒步", "Molignon 山小屋午餐"],
    ["自驾或公交进入需缴通行费", "草甸禁止采花", "下午 4 点后回程"]),
    "en": ("Alpe di Siusi", "Alpine meadow", "Alpe di Siusi Seiser Alm",
      "Europe's largest high-altitude meadow — paints of gold and green.",
      ["Compatsch cable car", "Panorama trail", "Molignon mountain hut lunch"],
      ["Pass required to drive in", "Don't pick flowers", "Leave by 16:00"])},
  "lago-carezza": {"zh": ("Lago di Carezza 布雷耶斯湖", "高山湖", "Lago di Carezza Karersee",
    "翡翠色湖水映照 Latemar 山，被称为彩虹湖。",
    ["湖西岸步道", "清晨平静水面倒影", "雨后最易见彩虹"],
    ["湖边停车位紧张", "湖边木栈道 30 分钟可走完", "绕湖一周约 1 小时"]),
    "en": ("Lago di Carezza", "Alpine Lake", "Lago di Carezza Karersee",
      "Emerald lake reflecting Latemar — nicknamed the Rainbow Lake.",
      ["Western shore trail", "Still morning mirror", "Rainbow after rain"],
      ["Parking limited", "Wooden boardwalk 30 min", "Loop trail ≈ 1h"])},
  # 威尼斯
  "venice-mestre": {"zh": ("Venice Mestre 火车站", "交通枢纽", "Venezia Mestre",
    "威尼斯本岛对岸的交通枢纽，住宿性价比远高于主岛。",
    ["10 分钟火车到圣卢西亚", "廉价餐厅众多", "酒店附近超市"],
    ["持火车票直接上岛", "不要被玻璃心群岛项目引导消费", "行李过桥走 Rialto 桥"]),
    "en": ("Venice Mestre Station", "Hub", "Venezia Mestre",
      "The mainland side of Venice — far better value than staying on the lagoon island.",
      ["10-min train to Santa Lucia", "Affordable restaurants", "Nearby supermarket"],
      ["Train ticket includes vaporetto on island", "Skip Murano/glass demos", "Cross Rialto with luggage"])},
  "venice-rialto": {"zh": ("威尼斯主岛", "水城", "Venice San Marco",
    "被亚得里亚海环抱的水城，圣马可广场与叹息桥见证千年商业帝国。",
    ["圣马可广场", "叹息桥", "里亚托桥", "学院桥看日落", "玻璃岛/彩色岛"],
    ["买 vaporetto 通票", "避开正午贡多拉", "小巷迷路贵 5%"]),
    "en": ("Venice Mainland Island", "Lagoon City", "Venice San Marco",
      "Floating city on the lagoon — Piazza San Marco and the Bridge of Sighs.",
      ["Piazza San Marco", "Bridge of Sighs", "Rialto Bridge", "Accademia Bridge sunset", "Murano/Burano"],
      ["Buy vaporetto pass", "Skip midday gondola", "Don't get lost in alleys"])},
  "venice-stmarks": {"zh": ("圣马可广场", "广场", "Piazza San Marco",
    "拿破仑称其为'欧洲最美客厅'，被圣马可大教堂与总督宫环抱。",
    ["圣马可大教堂黄金马赛克", "总督宫", "圣马可钟楼登顶看城"],
    ["现场买票排队 1 小时", "日落前 1 小时最美", "广场鸽子不要喂"]),
    "en": ("Piazza San Marco", "Square", "Piazza San Marco",
      "Napoleon called it Europe's drawing room — the only square called piazza.",
      ["Golden mosaics in Basilica", "Doge's Palace", "Bell Tower"],
      ["Skip-the-line online", "Sunset 1h before", "Don't feed pigeons"])},
  "venice-ponte": {"zh": ("学院桥", "桥", "Ponte dell'Accademia",
    "威尼斯四大名桥之一，最佳拍摄点：日落时桥上看大运河。",
    ["桥中心拍摄大运河", "日落时金色暖光", "夜晚华灯初上"],
    ["不要错过 18:30 黄金时刻", "桥上人多注意相机", "桥北端是学院美术馆"]),
    "en": ("Ponte dell'Accademia", "Bridge", "Ponte dell'Accademia",
      "One of four Venice bridges — best view down the Grand Canal at sunset.",
      ["Centre of bridge for canal shots", "Golden hour", "Twilight lamps"],
      ["Catch 18:30 golden moment", "Mind your camera", "Galleria dell'Accademia at north end"])},
  # 佛罗伦萨
  "florence-smn": {"zh": ("佛罗伦萨 SMN 火车站", "交通枢纽", "Firenze Santa Maria Novella",
    "佛罗伦萨中央火车站，步行可达圣母百花大教堂。",
    ["Trenitalia 自助取票", "广场附近咖啡馆", "行李寄存"],
    ["避开正街 FRA", "持票不要过街 FRA", "站台看大屏"]),
    "en": ("Firenze SMN Station", "Hub", "Firenze Santa Maria Novella",
      "Florence's central station — walking distance to the Duomo.",
      ["Trenitalia self-service", "Cafés on piazza", "Left luggage"],
      ["Check platforms on screens", "Italo/Trenitalia kiosks", "Buy water from kiosk"])},
  "uffizi": {"zh": ("乌菲兹美术馆", "美术馆", "Uffizi Gallery",
    "世界三大美术馆之一，波提切利的《维纳斯的诞生》《春》镇馆。",
    ["波提切利房间", "达·芬奇《博士来拜》", "拉斐尔《圣母》"],
    ["必须提前 14 天预约", "每张票对应时段", "入口在 1 号门"]),
    "en": ("Uffizi Gallery", "Museum", "Uffizi Gallery",
      "One of the world's top three art galleries — Venus and Spring by Botticelli.",
      ["Botticelli rooms", "Leonardo's Adoration", "Raphael's Madonna"],
      ["Book 14 days ahead", "Each ticket has a slot", "Entrance via Gate 1"])},
  "duomo": {"zh": ("圣母百花大教堂", "教堂", "Cattedrale di Santa Maria del Fiore",
    "文艺复兴发源地，穹顶由布鲁内莱斯基设计，至今仍是最大砖砌穹顶。",
    ["穹顶登顶 463 阶", "洗礼堂金门", "乔托钟楼"],
    ["联票含 5 个景点", "穹顶登顶赶在日落", "周日主日弥撒免费"]),
    "en": ("Duomo Florence", "Cathedral", "Cattedrale di Santa Maria del Fiore",
      "Cradle of the Renaissance — Brunelleschi's dome is still the largest brick dome.",
      ["Climb the dome (463 steps)", "Baptistery golden gates", "Giotto's bell tower"],
      ["Combo ticket covers 5 sites", "Sunset on the dome", "Free Sunday mass"])},
  "accademia": {"zh": ("学院美术馆", "美术馆", "Galleria dell'Accademia",
    "米开朗基罗《大卫》真迹所在地，文艺复兴雕塑巅峰。",
    ["《大卫》真迹", "《奴隶》系列", "音乐厅乐器收藏"],
    ["8:30 最早场排队", "门票 24 欧", "提前 b-ticket 预约"]),
    "en": ("Accademia Gallery", "Museum", "Galleria dell'Accademia",
      "Houses the original David by Michelangelo — Renaissance sculpture peak.",
      ["David original", "Slaves series", "Music instruments"],
      ["8:30 first slot", "€24 ticket", "Pre-book via b-ticket"])},
  "ponte-vecchio": {"zh": ("老桥", "桥", "Ponte Vecchio",
    "中世纪商人桥，至今仍有金匠店铺，是翡冷翠的标志。",
    ["桥上金匠店", "瓦萨利走廊", "阿尔诺河倒影"],
    ["黄昏最美", "桥两端最适合拍照", "清晨避开人潮"]),
    "en": ("Ponte Vecchio", "Bridge", "Ponte Vecchio",
      "Medieval merchant bridge — still houses goldsmith shops.",
      ["Goldsmith shops on bridge", "Vasari Corridor", "Arno reflection"],
      ["Best at dusk", "Best shots at both ends", "Empty at sunrise"])},
  "michelangelo-square": {"zh": ("米开朗基罗广场", "观景台", "Piazzale Michelangelo",
    "佛罗伦萨最佳日落点，俯瞰全城。",
    ["大卫像复制品", "日落全景", "台阶合影"],
    ["带外套", "早点占位", "注意防晒"]),
    "en": ("Piazzale Michelangelo", "Viewpoint", "Piazzale Michelangelo",
      "Florence's best sunset point — panoramic view of the city.",
      ["David replica", "Sunset panorama", "Staircase group photo"],
      ["Bring a jacket", "Arrive early for a spot", "Sunscreen required"])},
  "central-market": {"zh": ("中央市场", "市场", "Mercato Centrale",
    "一楼食材二楼餐厅，牛肚包发源地。",
    ["Nerbone 牛肚包", "二���意面", "现榨果汁"],
    ["二楼性价比高", "早午饭优选", "现金小额支付"]),
    "en": ("Mercato Centrale", "Market", "Mercato Centrale",
      "Local food downstairs, restaurants upstairs — birthplace of lampredotto.",
      ["Nerbone lampredotto", "Upstairs pasta", "Fresh juice"],
      ["Upstairs great value", "Lunch timing", "Small cash preferred"])},
  "republic-square": {"zh": ("共和广场", "广场", "Piazza della Repubblica",
    "佛罗伦萨最古老的广场，旋转木马经典。",
    ["旋转木马", "Caffè Gilli 老牌咖啡", "柱廊散步"],
    ["路边咖啡位加 5 欧", "周末有艺人", "傍晚灯光最美"]),
    "en": ("Piazza della Repubblica", "Square", "Piazza della Repubblica",
      "Florence's oldest square with the iconic carousel.",
      ["Carousel", "Caffè Gilli", "Colonnade walk"],
      ["Outdoor tables +€5", "Street performers", "Best at dusk"])},
  "signoria": {"zh": ("领主广场/旧宫", "广场", "Piazza della Signoria",
    "市政中心，《大卫》复制品在大门前。",
    ["旧宫卫队换岗", "海神喷泉", "兰奇回廊"],
    ["旧宫登塔 8 欧", "雕塑拍照免费", "凉廊躲雨"]),
    "en": ("Piazza della Signoria", "Square", "Piazza della Signoria",
      "Civic center — replica David stands at the entrance of Palazzo Vecchio.",
      ["Palazzo Vecchio guards", "Neptune Fountain", "Loggia dei Lanzi"],
      ["Tower climb €8", "Statues free", "Loggia shelters from rain"])},
  "santa-croce": {"zh": ("圣十字大殿", "教堂", "Basilica di Santa Croce",
    "佛罗伦萨的'先贤祠'，埋葬米开朗基罗/伽利略/马基雅维利。",
    ["米开朗基罗墓", "伽利略墓", "但丁衣冠冢"],
    ["皮件店老巷", "16 世纪风格", "傍晚人少"]),
    "en": ("Santa Croce", "Church", "Basilica di Santa Croce",
      "Florence's Pantheon — Michelangelo / Galileo / Machiavelli rest here.",
      ["Michelangelo's tomb", "Galileo's tomb", "Dante's cenotaph"],
      ["Leather shops in old alleys", "16th-century atmosphere", "Quiet at sunset"])},
  # 那不勒斯
  "naples-station": {"zh": ("那不勒斯中央火车站", "交通枢纽", "Napoli Centrale",
    "南意铁路枢纽，去庞贝/��普里/罗马均从此出发。",
    ["地铁 1 号线去港口", "Trenitalia 售票", "行李寄存"],
    ["注意扒手", "勿逗留袋", "站台看大屏"]),
    "en": ("Napoli Centrale", "Hub", "Napoli Centrale",
      "Southern Italy's main rail hub — to Pompeii / Capri / Rome.",
      ["Metro Line 1 to port", "Trenitalia tickets", "Left luggage"],
      ["Watch for pickpockets", "Check screens for platforms", "Use official taxi ranks"])},
  "capri-port": {"zh": ("卡普里港", "码头", "Marina Grande Capri",
    "卡普里主港，所有轮渡/快艇/缆车起点。",
    ["Funivia 缆车上山", "Porto Turistico", "餐厅露台"],
    ["回程船票提前买", "缆车 2 人/箱", "顶部海风大"]),
    "en": ("Capri Marina Grande", "Port", "Marina Grande Capri",
      "Capri's main port — ferries / boats / funivia all start here.",
      ["Funivia cable car up", "Porto Turistico", "Restaurant terraces"],
      ["Buy return ticket in advance", "Cable car max 2 per cabin", "Wind strong on top"])},
  "capri-piazzetta": {"zh": ("卡普里小镇", "小镇", "Piazzetta Capri",
    "卡普里镇中心，奢侈品与咖啡馆。",
    ["Umberto I 广场", "奢侈品橱窗", "Chiesa di Santo Stefano"],
    ["避开正午", "下午人少", "小路回船港"]),
    "en": ("Capri Piazzetta", "Town Center", "Piazzetta Capri",
      "Capri's town center — luxury shops and elegant cafés.",
      ["Piazza Umberto I", "Luxury windows", "Santo Stefano church"],
      ["Avoid midday", "Quieter afternoon", "Walk back via back streets"])},
  "anacapri": {"zh": ("阿纳卡普里", "山顶小镇", "Anacapri",
    "卡普里山顶小镇，比主岛更静谧。",
    ["索拉罗山缆车", "维拉圣米歇尔", "Casa Rossa"],
    ["索拉罗 7.5 欧", "蓝洞排队 2h+", "民宿阳台看日落"]),
    "en": ("Anacapri", "Hill Town", "Anacapri",
      "Capri's hilltop town — far more tranquil than the main island.",
      ["Mount Solaro chairlift", "Villa San Michele", "Casa Rossa"],
      ["Chairlift €7.5", "Blue Grotto queue 2h+", "Sunset from B&B balcony"])},
  "augustus-garden": {"zh": ("奥古斯都花园", "花园", "Giardini di Augusto",
    "卡普里必看花园，俯瞰法拉利���尼岩群。",
    ["Krupp 步道", "观景台", "仙人掌花坛"],
    ["门票 1.5 欧", "S 弯取景", "光线最好上午"]),
    "en": ("Augustus Garden", "Garden", "Giardini di Augusto",
      "Capri must-see garden — overlooking the Faraglioni rocks.",
      ["Via Krupp", "Observation deck", "Cactus beds"],
      ["€1.5 ticket", "S-curve shot", "Best light in morning"])},
  # 罗马
  "rome-termini": {"zh": ("罗马中央火车站", "交通枢纽", "Roma Termini",
    "罗马最大交通枢纽，地铁 A/B 线交汇。",
    ["地铁 B 线去斗兽场", "地铁 A 线去梵蒂冈", "行李寄存"],
    ["注意扒手", "行李看管", "站台看大屏"]),
    "en": ("Roma Termini", "Hub", "Roma Termini",
      "Rome's main station — Metro lines A and B intersect here.",
      ["Metro B to Colosseum", "Metro A to Vatican", "Left luggage"],
      ["Watch for pickpockets", "Secure luggage", "Check screens"])},
  "vatican-museum": {"zh": ("梵蒂冈博物馆", "博物馆", "Vatican Museums",
    "全球最小国家的博物馆群，西斯廷礼拜堂天花板为米开朗基罗巅峰。",
    ["西斯廷礼拜堂", "拉斐尔房间", "古希腊雕塑馆", "旋转楼梯"],
    ["必须提前预约", "首场 9:00 最佳", "门票 25 欧"]),
    "en": ("Vatican Museums", "Museum", "Vatican Museums",
      "The smallest state's museum group — Michelangelo's Sistine Chapel ceiling.",
      ["Sistine Chapel", "Raphael Rooms", "Classical sculpture", "Spiral staircase"],
      ["Book ahead required", "09:00 first slot is best", "€25 ticket"])},
  "st-peter": {"zh": ("圣彼得大教堂", "教堂", "St. Peter's Basilica",
    "全球最大教堂，米开朗基罗设计的穹顶与贝尔尼尼的青铜华盖。",
    ["穹顶登顶", "圣彼得铜像", "贝尔尼尼华盖", "哀悼基督"],
    ["穹顶电梯 + 楼梯", "周三教皇接见", "着装要求"]),
    "en": ("St. Peter's Basilica", "Basilica", "St. Peter's Basilica",
      "World's largest basilica — Michelangelo's dome and Bernini's bronze baldachin.",
      ["Climb the dome", "St. Peter's statue", "Bernini's baldachin", "Pietà"],
      ["Lift + stairs for dome", "Wednesday papal audience", "Dress code"])},
  "castel-angelo": {"zh": ("圣天使城堡", "古堡", "Castel Sant'Angelo",
    "哈德良陵墓改建城堡，顶层眺望圣彼得。",
    ["天使长青铜像", "教皇逃生密道", "顶层观景"],
    ["傍晚拍圣彼得", "联票优惠", "桥下景观"]),
    "en": ("Castel Sant'Angelo", "Castle", "Castel Sant'Angelo",
      "Hadrian's mausoleum turned fortress — top views over St. Peter's.",
      ["Archangel Michael statue", "Pope's escape route", "Roof view"],
      ["Sunset over St. Peter's", "Combo ticket", "Bridge view"])},
  "navona": {"zh": ("纳沃纳广场", "广场", "Piazza Navona",
    "贝尔尼尼的四河喷泉与圣阿涅塞教堂，罗马最巴洛克广场。",
    ["四河喷泉", "摩尔人喷泉", "海神喷泉"],
    ["街头画家表演", "下午茶位", "夜景华灯"]),
    "en": ("Piazza Navona", "Square", "Piazza Navona",
      "Bernini's Fountain of the Four Rivers — Rome's most Baroque square.",
      ["Fountain of the Four Rivers", "Moor's Fountain", "Neptune Fountain"],
      ["Street artists perform", "Afternoon tea seats", "Twilight lamps"])},
  "trevi": {"zh": ("特雷维许愿池", "喷泉", "Trevi Fountain",
    "全球最大巴洛克喷泉，背对投币许愿重回罗马。",
    ["许愿投币", "海神雕塑", "白色大理石"],
    ["清晨人少", "晚上华灯", "不要坐台阶"]),
    "en": ("Trevi Fountain", "Fountain", "Trevi Fountain",
      "World's largest Baroque fountain — toss a coin to return to Rome.",
      ["Coin toss", "Neptune statue", "White marble"],
      ["Best at dawn", "Lit at night", "Don't sit on steps"])},
  "spanish-steps": {"zh": ("西班牙广场", "广场", "Piazza di Spagna",
    "赫本吃冰淇淋的台阶，罗马时尚中心。",
    ["西班牙台阶", "破船喷泉", "奢侈品街"],
    ["禁止坐台阶", "G.FASSI 冰淇淋", "Condotti 街"]),
    "en": ("Spanish Steps", "Square", "Piazza di Spagna",
      "Audrey Hepburn's Spanish Steps — Rome's fashion center.",
      ["Spanish Steps", "Fontana della Barcaccia", "Luxury street"],
      ["No sitting on steps", "G.FASSI gelato", "Via Condotti"])},
  "pantheon": {"zh": ("万神庙", "古罗马建筑", "Pantheon",
    "至今仍保留完整穹顶的古罗马建筑，拉斐尔葬于此。",
    ["穹顶天眼", "拉斐尔墓", "皇帝陵寝"],
    ["免门票", "雨天看天眼", "正午阳光最佳"]),
    "en": ("Pantheon", "Ancient Roman", "Pantheon",
      "Best-preserved ancient Roman dome — Raphael is buried here.",
      ["Oculus", "Raphael's tomb", "Emperor tombs"],
      ["Free entry", "Rain pours through the oculus", "Noon light is best"])},
  "medici-villa": {"zh": ("美第奇别墅", "博物馆", "Villa Medici",
    "法国学院所在地，俯瞰西班牙广场。",
    ["花园", "露台", "古罗马雕塑"],
    ["日落最美", "联票优惠", "苹果树大道"]),
    "en": ("Villa Medici", "Museum", "Villa Medici",
      "French Academy HQ — overlooks the Spanish Steps.",
      ["Garden", "Terrace", "Roman sculptures"],
      ["Sunset is best", "Combo ticket", "Apple tree avenue"])},
  "colosseum": {"zh": ("罗马斗兽场", "古罗马遗址", "Colosseum",
    "古罗马帝国象征，角斗士与海战剧场。",
    ["竞技场/眺望", "地下层", "三层看台"],
    ["必须预约", "25 欧联票", "晨晨最美"]),
    "en": ("Colosseum", "Ancient Roman", "Colosseum",
      "Symbol of ancient Rome — gladiator arena and naval battles.",
      ["Arena floor", "Underground", "Three levels of stands"],
      ["Pre-book required", "€25 combo", "Best at dawn"])},
  "forum": {"zh": ("古罗马广场", "古罗马遗址", "Roman Forum",
    "古罗马政治中心，凯撒演讲与元老院。",
    ["元老院", "凯撒神庙", "帕拉迪诺山"],
    ["斗兽场合票", "清晨最美", "防晒必备"]),
    "en": ("Roman Forum", "Ancient Roman", "Roman Forum",
      "Ancient Rome's political heart — Caesar's orations and the Senate.",
      ["Senate", "Temple of Caesar", "Palatine Hill"],
      ["Combo with Colosseum", "Best at dawn", "Sun protection"])},
  "palatine": {"zh": ("帕拉迪诺山", "古罗马遗址", "Palatine Hill",
    "罗马七丘之首，皇帝宫殿遗址。",
    ["Domus Augustana", "Farnese 花园", "观景台"],
    ["与斗兽场合票", "走缓坡", "日落机位"]),
    "en": ("Palatine Hill", "Ancient Roman", "Palatine Hill",
      "First of the seven hills — emperors' palace ruins.",
      ["Domus Augustana", "Farnese Gardens", "Viewpoint"],
      ["Combo with Colosseum", "Walk slowly", "Sunset point"])},
  "bocca-verita": {"zh": ("真理之口", "古罗马雕塑", "Bocca della Verita",
    "古罗马下水道井盖，传言说谎会被咬手。",
    ["合影", "教堂", "井盖雕塑"],
    ["免费", "周末人少", "教堂免费"]),
    "en": ("Mouth of Truth", "Ancient Roman", "Bocca della Verita",
      "Ancient Roman sewer cover — legend bites liars' hands.",
      ["Photo op", "Church", "Marble mask"],
      ["Free", "Quiet on weekends", "Free church entry"])},
  "venezia-palace": {"zh": ("威尼斯广场", "广场", "Piazza Venezia",
    "罗马交通圆心，维克多·埃曼纽尔二世纪念堂。",
    ["祖国祭坛", "无名烈士墓", "骑马铜像"],
    ["俯瞰全城", "电梯到顶层", "卫兵换岗"]),
    "en": ("Piazza Venezia", "Square", "Piazza Venezia",
      "Rome's traffic hub and Victor Emmanuel II Monument.",
      ["Altar of the Fatherland", "Tomb of the Unknown Soldier", "Equestrian statues"],
      ["Panoramic view", "Lift to rooftop", "Guard change"])}
}

# 待办清单
todo_zh = [
  "办理签证（已确认）", "预订往返机票（EY871/EY81/EY86/EY870）",
  "Brixen 民宿预订", "威尼斯梅斯特雷 Staycity 预订",
  "佛罗伦萨 Rinascimento 民宿预订", "卡普里 B&B Il Sogno 预订",
  "罗马 Radisson Blu GHR 预订", "梵蒂冈博物馆提前预约",
  "乌菲兹美术馆提前预约", "学院美术馆提前预约",
  "多洛米蒂 BrixenCard", "欧元现金 + 国际信用卡",
  "境外旅行保险", "国际驾照翻译件",
  "便携 Wi-Fi / eSIM 卡", "电源转换插头（意标 L 型）",
  "防晒霜 + 雨伞", "舒适步行鞋"
]
todo_en = [
  "Visa (confirmed)", "Round-trip flights (EY871/EY81/EY86/EY870)",
  "Brixen apartment booking", "Venice Mestre Staycity booking",
  "Florence Rinascimento apartment booking", "Capri B&B Il Sogno booking",
  "Rome Radisson Blu GHR booking", "Vatican Museums advance booking",
  "Uffizi Gallery advance booking", "Accademia Gallery advance booking",
  "BrixenCard for Dolomites", "Euro cash + international credit card",
  "Travel insurance", "International driving permit translation",
  "Portable Wi-Fi / eSIM", "Power adapter (Type L)",
  "Sunscreen + umbrella", "Comfortable walking shoes"
]

# 贴士
tips_zh = [
  "意大利 9 月底已入秋，多洛米蒂山顶需备薄羽绒；10 月初罗马早晚 12-18°C，备薄外套。",
  "意大利时区 CEST（UTC+2），与北京相差 6 小时（夏令时）。",
  "餐厅午餐 13-15、晚餐 19-23 最忙，其余时段需确认营业。",
  "餐厅账单常含 coperto 餐位费 2-3€/人。",
  "热门餐厅建议提前 App 预约（TheFork 等）。",
  "意大利许多景点周日免费或优惠（如斗兽场每月第一个周日）。",
  "公共水龙头（nasone）遍布罗马，免费直饮。",
  "打车务必使用官方 APP（FreeNow、itTaxi），或在出租车站排队。",
  "意大利景点着装要求严格，教堂内勿露肩/膝。",
  "现金支付在小型餐厅/市集仍是主流，建议备 200-300 欧现金。",
  "包车/出租价格含行李不强制小费；餐厅小费 5-10%。",
  "意大利紧急电话：警察 112、医疗 118、消防 115。"
]
tips_en = [
  "Late September = autumn in Italy. Bring a light down jacket for Dolomites; 12–18°C in Rome in early October.",
  "Italy is on CEST (UTC+2) — 6 hours behind (during DST).",
  "Restaurants busy 13:00–15:00 (lunch) and 19:00–23:00 (dinner); confirm opening outside these.",
  "Coperto (cover charge) of €2–3/person is standard.",
  "Book popular restaurants on TheFork or similar apps.",
  "Many sites are free/discounted on Sundays (e.g., Colosseum first Sunday of the month).",
  "Rome's nasone drinking fountains serve free fresh water.",
  "Use official taxi apps (FreeNow / itTaxi) or queue at taxi ranks.",
  "Italy enforces strict dress codes — cover shoulders & knees in churches.",
  "Cash still king in small trattorias — keep €200–300 in cash.",
  "Taxis/private driver: luggage not extra. Restaurants: tip 5–10%.",
  "Italy emergency: 112 (police), 118 (medical), 115 (fire)."
]

# 住宿
stay_data = {
  "brixen-hotel": {"zh": ("Gerharts Premium City Living - center of Brixen",
    "Brixen", "Brixen Card 包含", "9.26 / 9.27 / 9.28 三晚", "611/晚",
    "含 BrixenCard，免费乘公交+多项折扣；免费停车。"),
    "en": ("Gerharts Premium City Living - center of Brixen",
      "Brixen", "Brixen Card included", "9.26 / 9.27 / 9.28 (3 nights)", "€611/night",
      "Includes BrixenCard (free bus + many discounts); free parking.")},
  "venice-hotel": {"zh": ("Staycity Aparthotels Venice Mestre",
    "Venice Mestre", "STAYCITY-2024-IT", "9.28 一晚", "453/晚",
    "梅斯特雷火车站步行 8 分钟；公寓式含厨房。"),
    "en": ("Staycity Aparthotels Venice Mestre",
      "Venice Mestre", "STAYCITY-2024-IT", "9.28 (1 night)", "€453/night",
      "8-min walk to Mestre station; apartment with kitchenette.")},
  "florence-hotel": {"zh": ("Rinascimento Apartments",
    "Florence", "RINA-2024-FIRENZE", "9.29 / 9.30 两晚", "409/晚",
    "近 SMN 火车站与中央市场；老建筑复式公寓。"),
    "en": ("Rinascimento Apartments",
      "Florence", "RINA-2024-FIRENZE", "9.29 / 9.30 (2 nights)", "€409/night",
      "Near SMN station and Mercato Centrale; historic duplex.")},
  "capri-hotel": {"zh": ("B&B Il Sogno",
    "Anacapri", "ILSOGNO-2024-CAPRI", "10.1 一晚", "358/晚",
    "山顶民宿含早餐；步行至缆车 10 分��。"),
    "en": ("B&B Il Sogno",
      "Anacapri", "ILSOGNO-2024-CAPRI", "10.1 (1 night)", "€358/night",
      "Hilltop B&B with breakfast; 10-min walk to chairlift.")},
  "rome-hotel": {"zh": ("Radisson Blu GHR Rome",
    "Rome", "RHG-2024-ROME", "10.2 / 10.3 / 10.4 三晚", "458-460/晚",
    "近中央火车站；含早。"),
    "en": ("Radisson Blu GHR Rome",
      "Rome", "RHG-2024-ROME", "10.2 / 10.3 / 10.4 (3 nights)", "€458–460/night",
      "Near Termini station; breakfast included.")}
}

# 交通票据
ticket_data = {
  "EY871": {"zh": ("flight", "香港 → 阿布扎比", "EY871",
    "9.25", "21:30-05:25+1", "HKG", "AUH",
    "4581 元/人", "阿提哈航空，提前 3h 到机场。"),
    "en": ("flight", "Hong Kong → Abu Dhabi", "EY871",
      "9.25", "21:30-05:25+1", "HKG", "AUH",
      "¥4581/p", "Etihad; arrive 3h early.")},
  "EY81": {"zh": ("flight", "阿布扎比 → 米兰马尔彭萨", "EY81",
    "9.26", "08:45-13:10", "AUH", "MXP",
    "4581 元/人", "T1 抵达，包车接机。"),
    "en": ("flight", "Abu Dhabi → Milan Malpensa", "EY81",
      "9.26", "08:45-13:10", "AUH", "MXP",
      "¥4581/p", "T1 arrival; private transfer.")},
  "EY86": {"zh": ("flight", "罗马 → 阿布扎比", "EY86",
    "10.5", "11:35-19:50", "FCO", "AUH",
    "4581 元/人", "FCO 机场，提前 3h。"),
    "en": ("flight", "Rome → Abu Dhabi", "EY86",
      "10.5", "11:35-19:50", "FCO", "AUH",
      "¥4581/p", "FCO airport; arrive 3h early.")},
  "EY870": {"zh": ("flight", "阿布扎比 → 香港", "EY870",
    "10.6", "08:30-19:30", "AUH", "HKG",
    "4581 元/人", "抵港后机场快线回市区。"),
    "en": ("flight", "Abu Dhabi → Hong Kong", "EY870",
      "10.6", "08:30-19:30", "AUH", "HKG",
      "¥4581/p", "Airport Express back to city.")},
  "Train-Roma-Florence": {"zh": ("train", "罗马 → 佛罗伦萨",
    "FRECCIAROSSA", "9.29", "07:38-09:39", "Roma Termini", "Firenze SMN",
    "270.25 €/人", "Italo 或 Trenitalia；早鸟票。"),
    "en": ("train", "Rome → Florence", "FRECCIAROSSA",
      "9.29", "07:38-09:39", "Roma Termini", "Firenze SMN",
      "€270.25/p", "Italo or Trenitalia early-bird.")},
  "Train-Florence-Naples": {"zh": ("train", "佛罗伦萨 → 那不勒斯",
    "FRECCIAROSSA", "10.1", "09:14-12:18", "Firenze SMN", "Napoli Centrale",
    "312.5 €/人", "Italo 9:14-12:18。"),
    "en": ("train", "Florence → Naples", "FRECCIAROSSA",
      "10.1", "09:14-12:18", "Firenze SMN", "Napoli Centrale",
      "€312.5/p", "Italo 9:14-12:18.")},
  "Ferry-Capri-Naples": {"zh": ("ferry", "卡普里 → 那不勒斯",
    "SNAV / NLG", "10.2", "16:30-17:30", "Capri Porto", "Napoli Molo Beverello",
    "约 25 €/人", "回程提前购票。"),
    "en": ("ferry", "Capri → Naples", "SNAV / NLG",
      "10.2", "16:30-17:30", "Capri Porto", "Napoli Molo Beverello",
      "≈€25/p", "Buy return in advance.")},
  "Ferry-Naples-Capri": {"zh": ("ferry", "那不勒斯 → 卡普里",
    "SNAV / NLG", "10.1", "14:40-15:30", "Napoli Molo Beverello", "Capri Porto",
    "约 24 €/人", "船票现场买亦可。"),
    "en": ("ferry", "Naples → Capri", "SNAV / NLG",
      "10.1", "14:40-15:30", "Napoli Molo Beverello", "Capri Porto",
      "≈€24/p", "Buy at dock.")},
  "Train-Naples-Rome": {"zh": ("train", "那不勒斯 → 罗马",
    "FRECCIAROSSA", "10.2", "19:20-20:30", "Napoli Centrale", "Roma Termini",
    "157 €/人", "高铁直达 70 分钟。"),
    "en": ("train", "Naples → Rome", "FRECCIAROSSA",
      "10.2", "19:20-20:30", "Napoli Centrale", "Roma Termini",
      "€157/p", "High-speed 70 min.")},
  "Dolomites-Car-MXP-Brixen": {"zh": ("car", "米兰 → Brixen 包车",
    "MILAN-BRIX-CAR", "9.26", "10:00 出发", "MXP 机场", "Brixen",
    "833 €/4人", "4 人均摊约 208 €/人；车程约 4 小时。"),
    "en": ("car", "Milan → Brixen car", "MILAN-BRIX-CAR",
      "9.26", "Depart 10:00", "MXP airport", "Brixen",
      "€833/4p", "≈€208/p split; ≈4h drive.")},
  "Dolomites-Car-Brixen-Venice": {"zh": ("car", "Brixen → 威尼斯 包车",
    "BRIX-VEN-CAR", "9.28", "午后出发", "Brixen", "Venice Mestre",
    "955 €/4人", "4 人均摊约 239 €/人；车程约 4.5 小时。"),
    "en": ("car", "Brixen → Venice car", "BRIX-VEN-CAR",
      "9.28", "Afternoon departure", "Brixen", "Venice Mestre",
      "€955/4p", "≈€239/p split; ≈4.5h drive.")}
}

# 地点全集 (经纬度)
locations_data = {
  "milano-malpensa": (45.6306, 8.7281, "airport", "Malpensa"),
  "milan-central": (45.4863, 9.2050, "train", "Milano Centrale"),
  "brixen": (46.7167, 11.6580, "town", "Brixen"),
  "seceda": (46.6333, 11.6500, "viewpoint", "Seceda"),
  "alpe-di-siusi": (46.5400, 11.6500, "viewpoint", "Alpe di Siusi"),
  "lago-carezza": (46.4186, 11.5789, "lake", "Lago di Carezza"),
  "venice-mestre": (45.4863, 12.2367, "train", "Mestre"),
  "venice-rialto": (45.4340, 12.3380, "town", "Venice"),
  "venice-stmarks": (45.4341, 12.3389, "landmark", "San Marco"),
  "venice-ponte": (45.4314, 12.3289, "bridge", "Accademia"),
  "florence-smn": (43.7764, 11.2486, "train", "Firenze SMN"),
  "uffizi": (43.7678, 11.2553, "museum", "Uffizi"),
  "duomo": (43.7731, 11.2559, "church", "Duomo"),
  "accademia": (43.7769, 11.2589, "museum", "Accademia"),
  "ponte-vecchio": (43.7680, 11.2531, "bridge", "Ponte Vecchio"),
  "michelangelo-square": (43.7629, 11.2650, "viewpoint", "Piazzale Michelangelo"),
  "central-market": (43.7768, 11.2527, "market", "Mercato Centrale"),
  "republic-square": (43.7731, 11.2532, "square", "Repubblica"),
  "signoria": (43.7697, 11.2564, "square", "Signoria"),
  "santa-croce": (43.7707, 11.2625, "church", "Santa Croce"),
  "naples-station": (40.8530, 14.2729, "train", "Napoli Centrale"),
  "capri-port": (40.5554, 14.2397, "port", "Marina Grande"),
  "capri-piazzetta": (40.5509, 14.2400, "town", "Piazzetta"),
  "anacapri": (40.5503, 14.2161, "town", "Anacapri"),
  "augustus-garden": (40.5474, 14.2397, "garden", "Augustus Garden"),
  "rome-termini": (41.9009, 12.5019, "train", "Roma Termini"),
  "fco": (41.8003, 12.2389, "airport", "FCO"),
  "vatican-museum": (41.9065, 12.4536, "museum", "Vatican"),
  "st-peter": (41.9022, 12.4539, "church", "St. Peter's"),
  "castel-angelo": (41.9031, 12.4663, "castle", "Castel Sant'Angelo"),
  "navona": (41.8992, 12.4731, "square", "Navona"),
  "trevi": (41.9009, 12.4833, "fountain", "Trevi"),
  "spanish-steps": (41.9058, 12.4823, "square", "Spanish Steps"),
  "pantheon": (41.8986, 12.4769, "ancient", "Pantheon"),
  "medici-villa": (41.9078, 12.4830, "museum", "Villa Medici"),
  "colosseum": (41.8902, 12.4922, "ancient", "Colosseum"),
  "forum": (41.8925, 12.4853, "ancient", "Roman Forum"),
  "palatine": (41.8893, 12.4875, "ancient", "Palatine"),
  "bocca-verita": (41.8881, 12.4811, "ancient", "Bocca Verita"),
  "venezia-palace": (41.8964, 12.4824, "square", "Venezia"),
  "hk": (22.3080, 113.9185, "airport", "HKG")
}

# ---- 生成 data.js ----
# 用 JSON 直接 dump Python 字典
def py_to_js(value, indent=0):
    """将 Python 值转换为 JS 字符串"""
    prefix = '  ' * indent
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    elif isinstance(value, bool):
        return 'true' if value else 'false'
    elif isinstance(value, (int, float)):
        return str(value)
    elif isinstance(value, list):
        if not value:
            return '[]'
        items = [py_to_js(x, indent+1) for x in value]
        return '[' + ', '.join(items) + ']'
    elif isinstance(value, tuple):
        # 元组转数组
        if not value:
            return '[]'
        items = [py_to_js(x, indent+1) for x in value]
        return '[' + ', '.join(items) + ']'
    elif isinstance(value, dict):
        if not value:
            return '{}'
        lines = ['{']
        items = []
        for k, v in value.items():
            k_str = json.dumps(k, ensure_ascii=False)
            v_str = py_to_js(v, indent+1)
            items.append(f'{prefix}  {k_str}: {v_str}')
        lines.append(',\n'.join(items))
        lines.append(prefix + '}')
        return '\n'.join(lines)
    else:
        return 'null'

# 构造 DICT
dict_zh = {
    "appName": "意大利旅行手册",
    "tagline": "四个女孩 · 12天 · 一段不会重来的故事",
    "navOverview": "总览", "navItinerary": "行程",
    "navTransport": "交通", "navStay": "住宿",
    "navTodo": "待办", "navTips": "贴士",
    "countdownTitle": "距离出发还有",
    "days": "天", "hours": "时", "minutes": "分", "seconds": "秒",
    "italyTime": "意大利时间", "chinaTime": "北京时间",
    "departureCity": "中国香港",
    "overviewMap": "行程总览地图",
    "showAllSpots": "显示全部地点",
    "backToOverview": "返回总览",
    "showAllPlaces": "显示所有地点",
    "hideAllPlaces": "收起所有地点",
    "mapNote": "⏱ 标注时间仅供参考",
    "dayOf": "第 {{n}} 天",
    "progress": "打卡进度",
    "checkIn": "○ 打卡",
    "checked": "✓ 已去过",
    "tags": {"flight": "航班", "book": "需提前订", "note": "注意", "info": "介绍", "nav": "导航"},
    "transit": "约 {{n}} 分钟",
    "flightBadge": "✈ 航班",
    "stayHotel": "晚住", "transfer": "→",
    "accommodationLabel": "住宿",
    "ticketLabel": "交通票据", "orderNo": "订单号",
    "todoTitle": "出行前待办",
    "tipsTitle": "旅行贴士",
    "footerNote": "本手册仅供私人旅行参考；时刻均为当地时间。",
    "spots": spots_data,
    "todoList": todo_zh,
    "tipsList": tips_zh,
    "stayInfo": stay_data,
    "ticketInfo": ticket_data
}

dict_en = {
    "appName": "Italy Travel Handbook",
    "tagline": "Four Girls · 12 Days · A Once-in-a-Lifetime Story",
    "navOverview": "Overview", "navItinerary": "Itinerary",
    "navTransport": "Transport", "navStay": "Stay",
    "navTodo": "Todo", "navTips": "Tips",
    "countdownTitle": "Departure in",
    "days": "d", "hours": "h", "minutes": "m", "seconds": "s",
    "italyTime": "Italy Time", "chinaTime": "Beijing Time",
    "departureCity": "Hong Kong, China",
    "overviewMap": "Itinerary Overview Map",
    "showAllSpots": "Show all places",
    "backToOverview": "Back to overview",
    "showAllPlaces": "Show all places",
    "hideAllPlaces": "Hide all places",
    "mapNote": "⏱ Times are approximate only",
    "dayOf": "Day {{n}}",
    "progress": "Progress",
    "checkIn": "○ Check in",
    "checked": "✓ Visited",
    "tags": {"flight": "Flight", "book": "Book ahead", "note": "Note", "info": "Info", "nav": "Map"},
    "transit": "≈ {{n}} min",
    "flightBadge": "✈ Flight",
    "stayHotel": "Stay", "transfer": "→",
    "accommodationLabel": "Stay",
    "ticketLabel": "Tickets & Orders", "orderNo": "Order #",
    "todoTitle": "Pre-trip Checklist",
    "tipsTitle": "Travel Tips",
    "footerNote": "For personal travel reference only. All times are local.",
    "spots": {k: v["en"] for k, v in spots_data.items()},
    "todoList": todo_en,
    "tipsList": tips_en,
    "stayInfo": {k: {"name": v["en"][0], "city": v["en"][1], "order": v["en"][2], "nights": v["en"][3], "price": v["en"][4], "note": v["en"][5]} for k, v in stay_data.items()},
    "ticketInfo": {k: {"type": v["en"][0], "label": v["en"][1], "no": v["en"][2], "date": v["en"][3], "time": v["en"][4], "from": v["en"][5], "to": v["en"][6], "price": v["en"][7], "note": v["en"][8]} for k, v in ticket_data.items()}
}

# 行程数据 (从原文)
MOVIES_DATA = [
  {"day": 1, "date": "2026-09-25", "weekday": "周五", "title": "启程 · 香港 → 阿布扎比",
   "cityLabel": "香港 / 阿布扎比", "cityKey": "hk-auh",
   "centerLat": 25.2528, "centerLng": 54.3773, "zoom": 3,
   "items": [
     {"time": "21:30", "zone": "HKT", "type": "flight",
      "title": "✈ EY871 香港 → 阿布扎比", "note": "全程约 7h55m；提前 3h 办登机。",
      "tags": ["flight"], "spot": None},
     {"time": "05:25+1", "zone": "GST", "type": "transit",
      "title": "抵达阿布扎比", "note": "转机时间约 3h20m。",
      "tags": ["note"], "spot": None}
   ],
   "stay": None, "transitNote": None},
  {"day": 2, "date": "2026-09-26", "weekday": "周六", "title": "阿布扎比 → ���兰 → 多洛米蒂",
   "cityLabel": "米兰 → 多洛米蒂 Brixen", "cityKey": "milan-brixen",
   "centerLat": 46.4, "centerLng": 11.0, "zoom": 7,
   "items": [
     {"time": "08:45", "zone": "GST", "type": "flight",
      "title": "✈ EY81 阿布扎比 → 米兰马尔彭萨", "note": "约 7h25m；包车司机举牌接机。",
      "tags": ["flight"], "spot": "milano-malpensa"},
     {"time": "10:00", "zone": "CEST", "type": "transit",
      "title": "🚗 包车前往 Brixen", "note": "4 人包车 €833；车程约 4 小时；沿途阿尔卑斯山景。",
      "tags": ["book"], "spot": None, "transit": 240},
     {"time": "14:00", "zone": "CEST", "type": "activity",
      "title": "抵达 Brixen 民宿", "note": "办理入住 Gerharts Premium City Living。",
      "tags": ["info"], "spot": "brixen"},
     {"time": "15:00", "zone": "CEST", "type": "activity",
      "title": "🚗 富内斯山谷 (Val di Funes)", "note": "St. Magdalena 教堂 + 日照金山。",
      "tags": ["nav"], "spot": None, "transit": 60},
     {"time": "18:30", "zone": "CEST", "type": "meal",
      "title": "晚餐 · Brixen 老城", "note": "尝试南提洛尔菜。",
      "tags": ["info"], "spot": "brixen"}
   ],
   "stay": "brixen-hotel",
   "transitNote": "米兰 → Brixen 4h 包车；沿途经过波尔察诺 (Bolzano)。"},
  {"day": 3, "date": "2026-09-27", "weekday": "周日", "title": "刀锋山 + 休斯高原",
   "cityLabel": "多洛米蒂 · Dolomites", "cityKey": "dolomites",
   "centerLat": 46.58, "centerLng": 11.65, "zoom": 10,
   "items": [
     {"time": "08:00", "zone": "CEST", "type": "transit",
      "title": "🚗 公交前往 Ortisei 缆车站", "note": "BrixenCard 包含；车程约 30 分钟。",
      "tags": ["info"], "spot": None, "transit": 30},
     {"time": "08:30", "zone": "CEST", "type": "activity",
      "title": "🪂 Seceda 刀锋山缆车上山", "note": "必看景点；山顶风大备外套。",
      "tags": ["book", "info"], "spot": "seceda"},
     {"time": "12:00", "zone": "CEST", "type": "meal",
      "title": "午餐 · Ortisei 山下", "note": "推荐 Café & Bistro。",
      "tags": ["info"], "spot": None, "transit": 60},
     {"time": "14:00", "zone": "CEST", "type": "transit",
      "title": "🚗 前往休斯高原", "note": "公交 + 缆车；Compatsch 上山。",
      "tags": ["book"], "spot": "alpe-di-siusi", "transit": 90},
     {"time": "15:00", "zone": "CEST", "type": "activity",
      "title": "🌄 休斯高原徒步", "note": "Panorama 步道；9 月底秋色渐染。",
      "tags": ["nav"], "spot": "alpe-di-siusi"},
     {"time": "18:00", "zone": "CEST", "type": "transit",
      "title": "🚗 返回 Brixen 民宿", "note": "公交全程约 1 小时。",
      "tags": [], "spot": None, "transit": 60}
   ],
   "stay": "brixen-hotel",
   "transitNote": "BrixenCard 包含所有公共交��。"},
  {"day": 4, "date": "2026-09-28", "weekday": "周一", "title": "布雷耶斯湖 → 威尼斯",
   "cityLabel": "多洛米蒂 → 威尼斯", "cityKey": "dolomites-venice",
   "centerLat": 45.6, "centerLng": 12.0, "zoom": 7,
   "items": [
     {"time": "07:00", "zone": "CEST", "type": "transit",
      "title": "🚗 出发前往布雷耶斯湖", "note": "车程约 30 分钟；清晨静谧最美。",
      "tags": [], "spot": None, "transit": 30},
     {"time": "07:30", "zone": "CEST", "type": "activity",
      "title": "🌊 布雷耶斯湖 (Lago di Carezza)", "note": "翡翠色湖水；雨后见彩虹。",
      "tags": ["info"], "spot": "lago-carezza"},
     {"time": "10:00", "zone": "CEST", "type": "transit",
      "title": "🚗 出发前往威尼斯", "note": "车程约 4.5 小时；中途午餐休息。",
      "tags": [], "spot": "venice-mestre", "transit": 270},
     {"time": "16:30", "zone": "CEST", "type": "activity",
      "title": "抵达 Staycity 民宿", "note": "办理入住。",
      "tags": ["info"], "spot": "venice-mestre"},
     {"time": "17:30", "zone": "CEST", "type": "transit",
      "title": "🚆 火车前往主岛", "note": "约 10 分钟；持票免费上岛。",
      "tags": [], "spot": "venice-rialto", "transit": 10},
     {"time": "18:30", "zone": "CEST", "type": "activity",
      "title": "🌅 学院桥看日落", "note": "威尼斯最经典取景地。",
      "tags": ["info"], "spot": "venice-ponte"},
     {"time": "20:00", "zone": "CEST", "type": "meal",
      "title": "晚餐 · 圣马可广场周边", "note": "推荐 Ristorante Quadri。",
      "tags": ["book"], "spot": "venice-stmarks"}
   ],
   "stay": "venice-hotel",
   "transitNote": "Brixen → 威尼斯 4.5h 包车 + 火车 10min。"},
  {"day": 5, "date": "2026-09-29", "weekday": "周二", "title": "威尼斯 → 佛罗伦萨",
   "cityLabel": "威尼斯 → 佛罗伦萨", "cityKey": "venice-florence",
   "centerLat": 43.77, "centerLng": 11.25, "zoom": 7,
   "items": [
     {"time": "07:00", "zone": "CEST", "type": "transit",
      "title": "🚆 火车 SMN 火车站", "note": "持票免费上岛。",
      "tags": [], "spot": "venice-rialto", "transit": 10},
     {"time": "07:38", "zone": "CEST", "type": "transit",
      "title": "🚆 Frecciarossa 前往佛罗伦萨", "note": "2 小时车程。",
      "tags": ["book"], "spot": None, "transit": 120},
     {"time": "09:39", "zone": "CEST", "type": "activity",
      "title": "抵达佛罗伦萨 SMN", "note": "步行前往民宿寄存行李。",
      "tags": [], "spot": "florence-smn"},
     {"time": "11:00", "zone": "CEST", "type": "meal",
      "title": "午餐 · 中央市场", "note": "Nerbone 牛肚包。",
      "tags": ["info"], "spot": "central-market"},
     {"time": "14:15", "zone": "CEST", "type": "activity",
      "title": "🎨 乌菲兹美术馆", "note": "波提切利房间必看。",
      "tags": ["book"], "spot": "uffizi"},
     {"time": "17:00", "zone": "CEST", "type": "activity",
      "title": "🌉 老桥 (Ponte Vecchio)", "note": "瓦萨利走廊；金匠店。",
      "tags": ["info"], "spot": "ponte-vecchio"},
     {"time": "18:30", "zone": "CEST", "type": "activity",
      "title": "🌅 米开朗基罗广场看日落", "note": "佛罗伦萨最佳日落点。",
      "tags": ["nav"], "spot": "michelangelo-square"}
   ],
   "stay": "florence-hotel",
   "transitNote": "威尼斯 SMN → 佛罗伦萨 SMN 火车 2 小时。"},
  {"day": 6, "date": "2026-09-30", "weekday": "周三", "title": "佛罗伦萨深度",
   "cityLabel": "佛罗伦萨", "cityKey": "florence",
   "centerLat": 43.77, "centerLng": 11.255, "zoom": 12,
   "items": [
     {"time": "08:30", "zone": "CEST", "type": "activity",
      "title": "🎨 学院美术馆 (大卫)", "note": "最早场；门票 24 欧；预约 b-ticket。",
      "tags": ["book", "info"], "spot": "accademia"},
     {"time": "11:00", "zone": "CEST", "type": "activity",
      "title": "⛪ 圣母百花大教堂", "note": "联票含 5 景点。",
      "tags": ["info", "book"], "spot": "duomo"},
     {"time": "13:00", "zone": "CEST", "type": "meal",
      "title": "午餐 · 中央市场", "note": "一楼食材二楼餐厅。",
      "tags": ["info"], "spot": "central-market"},
     {"time": "15:00", "zone": "CEST", "type": "activity",
      "title": "🌀 共和广场", "note": "旋转木马经典。",
      "tags": ["info"], "spot": "republic-square"},
     {"time": "16:00", "zone": "CEST", "type": "activity",
      "title": "👑 领主广场 / 旧宫", "note": "大卫复制品；旧宫登塔 8 欧。",
      "tags": ["info"], "spot": "signoria"},
     {"time": "17:00", "zone": "CEST", "type": "activity",
      "title": "✝ 圣十字大殿", "note": "先贤祠。",
      "tags": ["info"], "spot": "santa-croce"}
   ],
   "stay": "florence-hotel",
   "transitNote": "佛罗伦萨老城全部步行。"},
  {"day": 7, "date": "2026-10-01", "weekday": "周四", "title": "佛罗伦萨 → 卡普里岛",
   "cityLabel": "佛罗伦萨 → 卡普里", "cityKey": "florence-capri",
   "centerLat": 40.55, "centerLng": 14.25, "zoom": 9,
   "items": [
     {"time": "09:14", "zone": "CEST", "type": "transit",
      "title": "🚆 Italo 前往那不勒斯", "note": "约 3 小时。",
      "tags": ["book"], "spot": "naples-station", "transit": 180},
     {"time": "12:18", "zone": "CEST", "type": "transit",
      "title": "🚇 地铁 1 号线前往码头", "note": "约 20 分钟。",
      "tags": [], "spot": None, "transit": 20},
     {"time": "13:00", "zone": "CEST", "type": "meal",
      "title": "午餐 · 那不勒斯码头", "note": "披萨饼尝 Sfizio���",
      "tags": ["info"], "spot": None},
     {"time": "14:40", "zone": "CEST", "type": "transit",
      "title": "⛴ 轮渡前往卡普里", "note": "约 50 分钟；约 24 €/人。",
      "tags": ["book"], "spot": "capri-port", "transit": 50},
     {"time": "15:30", "zone": "CEST", "type": "transit",
      "title": "🚌 公交前往 Anacapri", "note": "排队 20min；约 16:30 到民宿。",
      "tags": ["note"], "spot": "anacapri", "transit": 60},
     {"time": "18:00", "zone": "CEST", "type": "activity",
      "title": "🌄 阿纳卡普里逛吃", "note": "如果来得及坐索拉罗缆车看日落。",
      "tags": ["nav", "book"], "spot": "anacapri"}
   ],
   "stay": "capri-hotel",
   "transitNote": "火车 + 地铁 + 轮渡 + 公交多段衔接。"},
  {"day": 8, "date": "2026-10-02", "weekday": "周五", "title": "卡普里岛 → 罗马",
   "cityLabel": "卡普里 → 罗马", "cityKey": "capri-rome",
   "centerLat": 41.9, "centerLng": 12.5, "zoom": 6,
   "items": [
     {"time": "08:30", "zone": "CEST", "type": "transit",
      "title": "🚠 索拉罗缆车上山", "note": "单程 13 分钟。",
      "tags": ["book"], "spot": None, "transit": 30},
     {"time": "09:00", "zone": "CEST", "type": "activity",
      "title": "🌅 索拉罗山顶", "note": "卡普里最高点。",
      "tags": ["nav"], "spot": None},
     {"time": "11:00", "zone": "CEST", "type": "transit",
      "title": "🚌 公交前往 Capri", "note": "约 30 分钟。",
      "tags": [], "spot": "augustus-garden", "transit": 30},
     {"time": "11:30", "zone": "CEST", "type": "activity",
      "title": "🌸 奥古斯都花园", "note": "S 弯取景；法拉利奥尼岩群。",
      "tags": ["info"], "spot": "augustus-garden"},
     {"time": "12:30", "zone": "CEST", "type": "meal",
      "title": "午餐 · 卡普里小镇", "note": "推荐 Faraglioni 露台餐厅。",
      "tags": ["info"], "spot": "capri-piazzetta"},
     {"time": "15:30", "zone": "CEST", "type": "transit",
      "title": "⛴ 轮渡回那不勒斯", "note": "16:30-17:30；约 25 €/人。",
      "tags": ["book"], "spot": "naples-station", "transit": 60},
     {"time": "17:30", "zone": "CEST", "type": "transit",
      "title": "🚇 地铁前往火车站", "note": "约 15 分钟。",
      "tags": [], "spot": None, "transit": 15},
     {"time": "19:20", "zone": "CEST", "type": "transit",
      "title": "🚆 高铁前往罗马", "note": "Frecciarossa 70 分钟。",
      "tags": ["book"], "spot": "rome-termini", "transit": 70},
     {"time": "20:30", "zone": "CEST", "type": "activity",
      "title": "抵达 Radisson Blu", "note": "办理入住。",
      "tags": ["info"], "spot": "rome-termini"}
   ],
   "stay": "rome-hotel",
   "transitNote": "卡普里 → 那不勒斯 轮渡 → 罗马 高铁全程约 4 小时。"},
  {"day": 9, "date": "2026-10-03", "weekday": "周六", "title": "梵蒂冈一日",
   "cityLabel": "梵蒂冈", "cityKey": "vatican",
   "centerLat": 41.905, "centerLng": 12.453, "zoom": 13,
   "items": [
     {"time": "08:30", "zone": "CEST", "type": "activity",
      "title": "⛪ 圣彼得大教堂", "note": "是否登顶？；约 2 小时。",
      "tags": ["info", "book"], "spot": "st-peter"},
     {"time": "11:00", "zone": "CEST", "type": "meal",
      "title": "午餐 · 梵蒂冈附近", "note": "推荐 Borgo Pio 老巷。",
      "tags": [], "spot": None},
     {"time": "13:00", "zone": "CEST", "type": "activity",
      "title": "🏛️ 梵蒂冈博物馆", "note": "含西斯廷礼拜堂；门票 25 欧。",
      "tags": ["book"], "spot": "vatican-museum"},
     {"time": "16:30", "zone": "CEST", "type": "activity",
      "title": "🏰 圣天使城堡", "note": "顶层眺望圣彼得。",
      "tags": ["info"], "spot": "castel-angelo"},
     {"time": "18:00", "zone": "CEST", "type": "activity",
      "title": "🎨 纳沃纳广场", "note": "四河喷泉；街头画家。",
      "tags": ["info"], "spot": "navona"},
     {"time": "19:30", "zone": "CEST", "type": "activity",
      "title": "🌊 特雷维许愿池", "note": "许愿投币；夜景华灯。",
      "tags": ["info"], "spot": "trevi"}
   ],
   "stay": "rome-hotel",
   "transitNote": "梵蒂冈步行 + 地铁 A 线。"},
  {"day": 10, "date": "2026-10-04", "weekday": "周日", "title": "罗马深度",
   "cityLabel": "罗马 · 古迹", "cityKey": "rome",
   "centerLat": 41.895, "centerLng": 12.482, "zoom": 13,
   "items": [
     {"time": "09:00", "zone": "CEST", "type": "activity",
      "title": "🛍️ 西班牙广场", "note": "赫本同款机位；G.FASSI 冰淇淋。",
      "tags": ["info"], "spot": "spanish-steps"},
     {"time": "10:30", "zone": "CEST", "type": "activity",
      "title": "🌊 特雷维许愿池", "note": "清晨人少。",
      "tags": ["info"], "spot": "trevi"},
     {"time": "12:00", "zone": "CEST", "type": "activity",
      "title": "🏛 万神庙", "note": "免门票；天眼下雨最美。",
      "tags": ["info"], "spot": "pantheon"},
     {"time": "13:30", "zone": "CEST", "type": "meal",
      "title": "午餐 · 万神殿附近", "note": "推荐 Da Tonino。",
      "tags": ["info"], "spot": None},
     {"time": "14:00", "zone": "CEST", "type": "activity",
      "title": "🌳 美第奇别墅", "note": "俯瞰西班牙广场。",
      "tags": ["info"], "spot": "medici-villa"},
     {"time": "16:00", "zone": "CEST", "type": "activity",
      "title": "🏛 罗马斗兽场", "note": "25 欧联票；提前预约。",
      "tags": ["book"], "spot": "colosseum"},
     {"time": "17:30", "zone": "CEST", "type": "activity",
      "title": "🏛 古罗马广场", "note": "凯撒演讲地；元老院。",
      "tags": ["info"], "spot": "forum"},
     {"time": "18:30", "zone": "CEST", "type": "activity",
      "title": "🌄 帕拉迪诺山", "note": "日落机位；俯瞰全城。",
      "tags": ["info"], "spot": "palatine"},
     {"time": "19:30", "zone": "CEST", "type": "activity",
      "title": "👄 真理之口", "note": "拍照必到。",
      "tags": ["info"], "spot": "bocca-verita"},
     {"time": "20:30", "zone": "CEST", "type": "meal",
      "title": "晚餐 · 威尼斯广场周边", "note": "推荐 Ristorante Corallo。",
      "tags": [], "spot": "venezia-palace"}
   ],
   "stay": "rome-hotel",
   "transitNote": "全部步行。"},
  {"day": 11, "date": "2026-10-05", "weekday": "周一", "title": "罗马 → 阿布扎比",
   "cityLabel": "罗马 → 阿布扎比", "cityKey": "rome-auh",
   "centerLat": 41.9, "centerLng": 12.5, "zoom": 11,
   "items": [
     {"time": "06:30", "zone": "CEST", "type": "meal",
      "title": "早餐 · 酒店", "note": "打包或简单用。",
      "tags": [], "spot": None},
     {"time": "07:00", "zone": "CEST", "type": "transit",
      "title": "🚖 前往 FCO 机场", "note": "Leonardo Express 或出租；约 45min。",
      "tags": ["book"], "spot": "fco", "transit": 45},
     {"time": "08:30", "zone": "CEST", "type": "activity",
      "title": "✈ EY86 罗马 → 阿布扎比", "note": "11:35 起飞；约 5h15m。",
      "tags": ["flight"], "spot": "fco"},
     {"time": "11:35", "zone": "CEST", "type": "flight",
      "title": "✈ 起飞", "note": "全程 5h15m；机上餐。",
      "tags": ["flight"], "spot": None}
   ],
   "stay": None,
   "transitNote": "酒店 → FCO 机场约 45min。"},
  {"day": 12, "date": "2026-10-06", "weekday": "周二", "title": "阿布扎比 → 香港 · 回家",
   "cityLabel": "阿布扎比 → 香港", "cityKey": "auh-hk",
   "centerLat": 24.5, "centerLng": 54.5, "zoom": 5,
   "items": [
     {"time": "08:30", "zone": "GST", "type": "flight",
      "title": "✈ EY870 阿布扎比 → 香港", "note": "约 7h。",
      "tags": ["flight"], "spot": "hk"},
     {"time": "19:30", "zone": "HKT", "type": "activity",
      "title": "🛬 抵达香港", "note": "回家！",
      "tags": ["info"], "spot": "hk"}
   ],
   "stay": None,
   "transitNote": "全程飞行日。"}
]

# 生成 JS 输出
zh_dict_js = py_to_js(dict_zh)
en_dict_js = py_to_js(dict_en)
itinerary_js = py_to_js(MOVIES_DATA)
locations_js = py_to_js({k: {"lat": v[0], "lng": v[1], "kind": v[2], "name": v[3]} for k, v in locations_data.items()})

content = f"""/* ===========================================================
   意大利旅行手册 - 数据对象 (IIFE 内引用)
   所有坐标都是 [lat, lng]
   =========================================================== */

const DICT = {{
  zh: {zh_dict_js},
  zht: "zh-tw",  // 繁体走 zh 路 -> 字形转换
  en: {en_dict_js}
}};

const ITINERARY = {itinerary_js};

const LOCATIONS = {locations_js};
"""

with open('C:/Users/fan77/WorkBuddy/2026-09-22-15-02-23/itinerary/data.js', 'w', encoding='utf-8') as f:
    f.write(content)

print("Generated data.js")
# 验证
try:
    exec(content.replace('const ', 'globalThis.'))
    print('OK')
    print('DICT keys:', list(globalThis.DICT.keys()))
    print('ITINERARY days:', len(globalThis.ITINERARY))
    print('LOCATIONS count:', len(globalThis.LOCATIONS))
except Exception as e:
    print('Error:', e)
    import traceback
    traceback.print_exc()